### ISSUE TITLE
Demo URL 404

### ISSUE THREAD

**Issue by contiki9** [loup-brun/buttons#1] opened 2017-08-24 10:24 UTC
There is no link of the demo

https://labs.loupbrun.ca/buttons/

**Comment by loup-brun** [comment] 2017-08-24 12:57
Hi,

Thank you for the notification. There was an issue the other day with the server, it should be fixed now. Please let me know if the demo still isn't working.

Regards,

@loup-brun

**Comment by contiki9** [comment] 2017-08-26 09:52
Hi,
Sorry, I still can not see the demo page.

I will send my screen capture
![image](https://user-images.githubusercontent.com/6760605/29740348-88ea5304-8a8f-11e7-822d-f596625f1c8e.png)

**Comment by loup-brun** [comment] 2017-08-26 15:06
Indeed, the issue is still persisting – I will get to it soon (it's a server problem). Thanks!

**Closed** 2017-08-26 16:57 UTC
